import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { Toolbar } from '../../components/Toolbar'
import { useEffect, useState } from 'react'
import Router from 'next/router'



export default function Home() {
    const [userData, setUserData] = useState({})
    const [recipes, setRecipes] = useState([])

    async function getUserDetails() {
        let res = await fetch("/api/UserDetails", {
            headers: { 'edgetoken': localStorage.getItem('Token') || '' }
        })
        let data = await res.json()
        console.log(data)
        setUserData(data.res)
    }

    async function getRecipeDetails() {
        let res = await fetch("/api/Recipe", {
            headers: { 'edgetoken': localStorage.getItem('Token') || '' }
        })
        let data = await res.json()
        console.log(data)
        setRecipes(data.res)
    }



    useEffect(() => {
        if (localStorage.getItem('Token') === null || localStorage.getItem('Token') === undefined) {

            Router.push("/login")
        }

        getUserDetails();
        // getRecipeDetails();
        // console.log(await data)
    }, []) // <-- empty dependency array


    const redirect = async function (page) {
        Router.push(page)
    };




    return (
        <div>
            <Toolbar>
            </Toolbar>
            <div className={styles.container}>
                <Head>
                    <title>Recipes</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/avo.ico" />
                </Head>


                <main className={styles.main}>
                    <div className={styles.cardGroup}>
                        <object type="image/svg+xml" data="/loading.svg">svg-animation</object>


                    </div>
                    {/* <Button onClick={() => console.log(recipes)}> show Recipes</Button> */}
                </main>

                <footer className={styles.footer}>
                    <a
                        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        target="_blank"
                        rel="noopener noreferrer"
                    >

                    </a>
                </footer>
            </div>
        </div>
    )
}
