import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'



import { Toolbar } from '../Toolbar'
import { useEffect, useState } from 'react'
import Form from 'react-bootstrap/Form';
import Button from 'react-bootstrap/Button';
import Router from 'next/router'
import Card from 'react-bootstrap/Card'













import Container from 'react-bootstrap/Container'
import Row from 'react-bootstrap/Row'
import Col from 'react-bootstrap/Col'



export default function Home() {
    const [userData, setUserData] = useState({})
    const [gameData, setGameData] = useState({})
    
    const [imageData, setImageData] = useState()

    async function getUserDetails() {
        var data = await (await fetch("/api/UserDetails?EDGEtoken=" + localStorage.getItem('Token'))).json()
        console.log(data)
        setUserData(data.res)
    }

    async function getRecipeDetails() {
        var data = await (await fetch("/api/Recipe?EDGEtoken=" + localStorage.getItem('Token'))).json()
        console.log(data)
        setRecipes(data.res)
    }



    useEffect(() => {
        if (localStorage.getItem('Token') === null || localStorage.getItem('Token') === undefined) {
            alert("please re-log in")
            Router.push("/login")
        }

        getUserDetails();
        // getRecipeDetails();
        // console.log(await data)
    }, []) // <-- empty dependency array


    const redirect = async function (page) {
        Router.push(page)
    };




    return (
        <div>
            <Toolbar>
            </Toolbar>
            <div className={styles.container}>
                <Head>
                    <title>Recipes</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/avo.ico" />
                </Head>








                <main className={styles.main}>

                    <Container>
                        <h1>General</h1>
                        <Row>
                            <Col>
                                <Card style={{ maxWidth: '100vw', color: "black" }}>
                                    {/* <Card.Img variant="top" src="/edge_login_image.png" /> */}
                                    <Card.Body>
                                        {/* <Card.Title>Add ingredient</Card.Title> */}

                                        <Form>

                                            <Form.Group className="mb-3" id="formGameName">
                                                <Form.Label>Game Name</Form.Label>
                                                <Form.Control name="gameName" id="gameName" type="text" placeholder="Enter Game Name" onChange={(e) => setRecipeName(e.target.value)} />

                                            </Form.Group>

                                            
                                            <Form.Group className="mb-3" id="formBasicEmail">
                                                <Form.Label>Measure</Form.Label>
                                                <Form.Control name="ingredAmount" id="ingredAmount" type="text" placeholder="Enter Amount" required/>
                                                
                                                <Form.Select aria-label="Default select example" name="ingredAmountType" id="ingredAmountType" required>

                                                    <option value="x">Amount (xN)</option>
                                                    <option value="g">Grams</option>
                                                    <option value="c">Cups</option>
                                                    <option value="tbs">Tablespoon</option>
                                                    <option value="tsp">Teaspoon</option>
                                                    <option value="L">Litres</option>

                                                </Form.Select>
                                            </Form.Group>

                                        </Form>



                                    </Card.Body>
                                </Card>
                            </Col>
                        </Row>

                        <Row>
                            <Col>
                                <h1>Add Image</h1>
                                <input accept="image/*" type="file" onChange={(e) => { getBase64(e.target.files[0], (data) => setImageData(data)) }} />

                            </Col>
                            <Col>
                                {/* {image!==undefined?<Image src={image}></Image>: <h4>no image</h4>} */}
                                <Card style={{ maxWidth: '20em', color: "black", right: "0px", float: "right" }}>
                                    <img src={imageData} style={{ maxWidth: "20em", maxHeight: "20em" }} />
                                </Card>

                            </Col>
                        </Row>
                        <Row>

                            <Button onClick={() => onSubmitRecipe()}> Save </Button>

                        </Row>

                    </Container>
                    {/* <Button onClick={()=>console.log(recipeName)}>recipe name</Button> */}
                </main>

                <footer className={styles.footer}>
                    <a
                        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        target="_blank"
                        rel="noopener noreferrer"
                    >

                    </a>
                </footer>
            </div>
        </div>
    )
}
