import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { Toolbar } from '../Toolbar'
import { useEffect, useState } from 'react'
import { Card, CardContent, CardTitle } from '../../components/ui/card'
import Router from 'next/router'

export default function Home() {
    const [userData, setUserData] = useState({})
    const [recipes, setRecipes] = useState([])

    async function getUserDetails() {
        let data = await (await fetch("/api/UserDetails?EDGEtoken=" + localStorage.getItem('Token'))).json()
        setUserData(data.res)
    }

    useEffect(() => {
        if (localStorage.getItem('Token') === null || localStorage.getItem('Token') === undefined) {
            Router.push("/login")
        }
        getUserDetails();
    }, [])

    const redirect = async function (page) {
        Router.push(page)
    };

    return (
        <div>
            <Toolbar />
            <div className={styles.container}>
                <Head>
                    <title>Recipes</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/avo.ico" />
                </Head>

                <main className={styles.main}>
                    <div className={styles.cardGroup}>
                        <div style={{ padding: "0.5vh" }}>
                            <Card
                                className="w-[15rem] h-[15rem] cursor-pointer text-black dark:text-white"
                                onClick={() => redirect("/game/create")}
                            >
                                <CardContent className="flex flex-col items-center justify-center h-full">
                                    <CardTitle>Create Game</CardTitle>
                                </CardContent>
                            </Card>
                        </div>

                        <div style={{ padding: "0.5vh" }}>
                            <Card
                                className="w-[15rem] h-[15rem] cursor-pointer text-black dark:text-white"
                                onClick={() => redirect("/game/join")}
                            >
                                <CardContent className="flex flex-col items-center justify-center h-full">
                                    <CardTitle>Join Game</CardTitle>
                                </CardContent>
                            </Card>
                        </div>
                    </div>
                </main>

                <footer className={styles.footer}>
                    &copy; {new Date().getFullYear()} Recipebook
                </footer>
            </div>
        </div>
    )
}
