import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'



import { Toolbar } from './Toolbar'
import { useEffect, useState } from 'react'
import Form from 'react-bootstrap/Form';
import Button from 'react-bootstrap/Button';
import Router from 'next/router'
import Card from 'react-bootstrap/Card'



export default function Home() {
    const [userData, setUserData] = useState({})
    const [recipes, setRecipes] = useState([])
    const [allIngreds, setAllIngreds] = useState([])
    const [Headers, setHeaders] = useState([])

    async function getUserDetails() {
        var data = await (await fetch("/api/UserDetails?EDGEtoken=" + localStorage.getItem('Token'))).json()
        console.log(data)
        setUserData(data.res)
    }

    async function getRecipeDetails() {
        var data = await (await fetch("/api/Recipe?EDGEtoken=" + localStorage.getItem('Token'))).json()
        console.log(data)
        setRecipes(data.res)
    }

    async function getAllIngredients() {
        var data = await (await fetch(`/api/Ingredients/?EDGEtoken=` + localStorage.getItem('Token'))).json()
        setAllIngreds(data.res)
        // console.log(data)
        // setRecipes(data.res)
    }

    async function getIngredient(e) {
        // e.preventDefault();

        console.log(e)
        let IngredQuery = e.target.ingredName.value


        var data = await (await fetch(`/api/Ingredients/${IngredQuery}?EDGEtoken=` + localStorage.getItem('Token'))).json()
        console.log(data)
        setAllIngreds([...allIngreds.concat(data.res)])
        console.log(data)
        // setRecipes(data.res)
    }



    useEffect(() => {
        if (localStorage.getItem('Token') === null || localStorage.getItem('Token') === undefined) {
            alert("please re-log in")
            Router.push("/login")
        }

        getUserDetails();
        getAllIngredients()
        setHeaders([
            // "_id",
            // "id",
            "name",
            "source",
            "price",
            "quantity",
            "quantity_type",
            "search_term",
            // "created_at",
            // "updated_at",
            // "__v"
        ])
        // getRecipeDetails();
        // console.log(await data)
    }, []) // <-- empty dependency array


    const redirect = async function (page) {
        Router.push(page)
    };

    


    return (
        <div>
            <Toolbar>
            </Toolbar>
            <div className={styles.container}>
                <Head>
                    <title>Ingredients</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>








                <main className={styles.main}>
                    <Form onSubmit={(e) => getIngredient(e)}>
                        <Form.Group className="mb-3" id="formBasicEmail">
                            <Form.Label>Name</Form.Label>
                            <Form.Control name="ingredName" id="ingredName" type="text" placeholder="Enter ingredient Name" required />

                        </Form.Group>
                        <Button variant="primary" type="submit">
                            Submit
                        </Button>
                    </Form>
                    <table>
                        {Headers.map((key) => {
                            return (
                                <>
                                    <th className={styles.td}>
                                        {key}
                                    </th>
                                </>
                            )
                        })}
                        {allIngreds.map((ingredient) => {
                            let res = Headers.map((key) => {
                                return (
                                    <>
                                        <td className={styles.td}>
                                            {ingredient[key]}
                                        </td>
                                    </>
                                )
                            })
                            return (
                                <>
                                <tr style={{ padding: "0.5vh" }}>
                                    {res}
                                </tr>
                                </>
                            )

                        })}

                    </table>
                </main>

                <footer className={styles.footer}>
                    <a
                        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        target="_blank"
                        rel="noopener noreferrer"
                    >

                    </a>
                </footer>
            </div>
        </div>
    )
}
