import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Table from 'react-bootstrap/Table';

import { Toolbar } from './Toolbar'
import { useEffect, useState } from 'react'
import Form from 'react-bootstrap/Form';
import Button from 'react-bootstrap/Button';
import Router from 'next/router'
import Card from 'react-bootstrap/Card'
import { IngredientSearchList } from "../components/IngredientSearchList"
import IngredientResearchComponent from './ingredientResearchComponent';


export default function Home() {
    const [userData, setUserData] = useState({})
    const [searchTerm, setSearchTerm] = useState("")
    async function getUserDetails() {
        let data = await (await fetch("/api/UserDetails?EDGEtoken=" + localStorage.getItem('Token'))).json()
        console.log(data)
        setUserData(data.res)
    }

    useEffect(() => {
        if (localStorage.getItem('Token') === null || localStorage.getItem('Token') === undefined) {
            alert("please re-log in")
            Router.push("/login")
        }

        getUserDetails();
    }, []) // <-- empty dependency array


    const redirect = async function (page) {
        Router.push(page)
    };

    async function handleGetIngredient(e){
        let ingredient = {
            "name": e.ingredName
        }
        let data = await (await fetch(`/api/Ingredients/?name=${ingredient.name}&qType=${ingredient.quantity_type}&returnN=${results}&quantity=${ingredient.quantity}&supplier=${enabledSuppliers.join(',')}&EDGEtoken=${Token}`)).json()
    }




    return (
        <div>
            <Toolbar>
            </Toolbar>
            <div className={styles.container}>
                <Head>
                    <title>Ingredients</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/avo.ico" />
                </Head>
                <main className={styles.main}>
                <Card className="p-4" style={{ maxWidth: '80%', margin: '0 auto', borderRadius: '10px', boxShadow: '0 8px 16px rgba(0,0,0,0.2)' }}>
          <Card.Body>
            <h1 className="text-center mb-4" style={{ color: '#007bff' }}>Ingredient Explorer</h1>
            <p className="text-center text-muted mb-4">
              Check out how much shit costs at either, "Woolworths", "Aldi", "Panetta" or "IGA". 
            </p>
            
            {/* Render Ingredient Research Component */}
            <div className="mt-4">
              <IngredientResearchComponent/>
            </div>
          </Card.Body>
        </Card>

                </main>

                <footer className={styles.footer}>
                    <a
                        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        target="_blank"
                        rel="noopener noreferrer"
                    >

                    </a>
                </footer>
            </div>
        </div>
    )
}
