

import Router from 'next/router'
import styles from '../styles/Login.module.css'
import Head from 'next/head'
import Image from 'next/image'
import Card from 'react-bootstrap/Card'
import Button from 'react-bootstrap/Button'
import Form from 'react-bootstrap/Form';
import { useState } from 'react';


export default function signup() {
    const onSubmit = async function(e) {
        e.preventDefault();
        
        console.log(e.target)

        var data = await(await fetch("/api/signup", {
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                "email": e.target.email.value,
                "password": e.target.password.value,
                "username": e.target.username.value,
            })
        })).json()
        console.log(data)
        if (data.success === false){
            alert(await data.message)
            // console.log(await data)
        } else if (data.success === true){
            localStorage.setItem('Token', data.data.token);
            Router.push('/')
        }
        
    };

    const redirect = async function(page) {
        Router.push(page)
    };

    


    return (
        <div className={styles.container}>
            <Head>
                <title>Register</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/avo.ico" />
            </Head>







            {/* style={{"backgroundImage": "url('bg_img.png')", "backgroundBlendMode": "overlay"}} */}
            <main className={styles.main_flex} >
                <Card style={{ width: '40vh' }}>
                    {/* <Card.Img variant="top" src="/edge_login_image.png" /> */}
                    <Card.Body>
                        <Card.Title>Sign Up</Card.Title>

                        <Form onSubmit={(e)=>onSubmit(e)}>
                        <Form.Group className="mb-3" id="formBasicEmail">
                                <Form.Label>Username</Form.Label>
                                <Form.Control name="username" id="username" type="text" placeholder="Enter username"/>

                            </Form.Group>

                            <Form.Group className="mb-3" id="formBasicEmail">
                                <Form.Label>Email address</Form.Label>
                                <Form.Control name="email" id="email" type="email" placeholder="Enter email" />

                            </Form.Group>

                            <Form.Group className="mb-3" id="formBasicPassword">
                                <Form.Label>Password</Form.Label>
                                <Form.Control name="password" id="password" type="password" placeholder="Password"/>
                            </Form.Group>
                            {/* <Form.Group className="mb-3" controlId="formBasicCheckbox">
                                <Form.Check type="checkbox" label="Check me out" />
                            </Form.Group> */}
                            <Button variant="primary" type="submit">
                                Submit
                            </Button>
                            <Button variant="secondary" style={{ "float": "right" }} onClick={()=>redirect("/login")}>
                                Return to Login
                            </Button>
                        </Form>



                    </Card.Body>
                </Card>

            </main>


        </div>
    )
}
